---
apiVersion: v1
kind: Pod
metadata: 
  name: env-pod
spec:
  containers:
    - name: pod-env
      image: httpd 
      env:
        - name: 
          value: rootroot


      ports:
        - containerPort: 80
