apiVersion: v1
kind: Pod
metadata: 
  name: nginx
spec:
  restartPolicy: OnFailure
  containers:
    - name: always
      image: alpine      
      ports:
        - containerPort: 80
  args:
    - sleep
    - 3s
